name: lando-php
events:
  post-start:
    - defaults: php -i | grep memory_limit | grep -e "-1"
services:
  defaults:
    type: php
  cli:
    type: php
    via: cli
    run_as_root:
      - ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime
      - echo "America/New_York" > /etc/timezone
  cliold:
    type: php:5.6
    via: cli
  custom:
    type: php:7.1
    via: nginx
    ssl: true
    xdebug: true
    webroot: web
    config:
      php: config/php.ini
    overrides:
      image: devwithlando/php:7.1-fpm-2
      environment:
        DUALBLADE: maxim
  custom74:
    type: php:7.4
  composer:
    type: php:7.0
    composer:
      phpunit/phpunit: "*"
tooling:
  php:
    service: defaults
