name: acquia

# add in the varnish edge
proxy:
  edge:
    - edge.acquia.lndo.site

# start with basic lamp recipe
recipe: lamp
config:
  php: 7.1 # or other as appropriate
  # modify webroot sub dir as needed
  # webroot: docroot
  database: mysql:5.6

# add additional auxiliary services
services:
  edge:
    type: varnish:4.1
    backends:
      - appserver
    ssl: true
  cache:
    type: memcached:1.4
