name: lempdbandcache
recipe: lemp
config:
  webroot: web
  php: '5.6'
services:
  cache:
    type: redis
    persist: true
  node:
    type: node:6.10
tooling:
  redis-cli:
    service: cache
  node:
    service: node
  npm:
    service: node
