# elasticsearch example
name: elasticsearch

# Spin up a basic nodes server with elasticsearch backend
services:

  # Spin up a elasticsearch container called "search"
  # NOTE: "search" is arbitrary, you could just as well call this "theboss" or "eljefe"
  search:

    # Use version
    type: elasticsearch

    # Optionally allow access to the cache at localhost:9999
    # You will need to make sure port 9999 is open on your machine
    #
    # You can also set `portforward: true` to have Lando dynamically assign
    # a port. Unlike specifying an actual port setting this to true will give you
    # a different port every time you restart your app
    portforward: true

    # Memsize
    mem: 1026m

    # Plugins
    # plugins:
    #   - plugin1
    #   - plugin2

    # Optionally load in a custom config file. This is relative to the app root.
    #
    config:
      server: config/custom.yml

