name: lando-elasticsearch
services:
  defaults:
    type: elasticsearch
  patch:
    type: elasticsearch:5.6.14
  custom:
    type: elasticsearch
    portforward: true
    mem: 1026m
    # Plugins
    # plugins:
    #   - plugin1
    #   - plugin2
    config:
      server: config/custom.yml

