name: lando
env_file:
  - lando.env
excludes:
  - node_modules
proxy:
  api:
    - api.lndo.site:8011
  blog:
    - blog.lndo.site:8007
  docs:
    - docs.lndo.site:8008
  site:
    - site.lndo.site:8009
  metrics:
    - metrics.lndo.site:8010
services:
  cli:
    type: node:10
    build:
      - yarn install
  api:
    type: node:10
    command: yarn run dev:api
    overrides:
      environment:
        LANDO_API_PORT: 8011
    port: 8011
  blog:
    type: node:10
    command: "su -c 'cd /app && yarn --link-folder /home/node --cache-folder /home/node dev:blog' --preserve-environment - node"
    port: 8007
    overrides:
      environment:
        LANDO_API: https://api.lndo.site
  docs:
    type: node:10
    command: "su -c 'cd /app && yarn --link-folder /home/node --cache-folder /home/node dev:docs' --preserve-environment - node"
    port: 8008
    overrides:
      environment:
        LANDO_API: https://api.lndo.site
  site:
    type: node:10
    command: "su -c 'cd /app && yarn --link-folder /home/node --cache-folder /home/node dev:site'  --preserve-environment - node"
    port: 8009
    overrides:
      environment:
        LANDO_API: https://api.lndo.site
  metrics:
    type: node:10
    command: yarn run dev:metrics
    overrides:
      environment:
        LANDO_METRICS_PORT: 8010
    port: 8010
  platform:
    type: php:7.3
    via: cli
    build:
      - mkdir -p /var/www/.platformsh/bin
      - curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.40.4/platform.phar
      - chmod ug+x /var/www/.platformsh/bin/platform
tooling:
  platform:
    service: platform
    description: Run Platform CLI commands
    cmd: /var/www/.platformsh/bin/platform
  # should these be able to run on either service once we've got the website in here too?
  yarn:
    service: cli
  node:
    service: cli
  vuepress:
    service: cli

