name: lando.dev
proxy:
  docs:
    - docs.lndo.site:4000
services:
  docs:
    type: node:10
    install_dependencies_as_me:
      - yarn
      - node ./scripts/docs.js && yarn gitbook install
    command: yarn gitbook serve
  cli:
    type: node:10
tooling:
  yarn:
    service: cli
