language: node_js
dist: xenial
matrix:
  include:
  - os: linux
    env: LANDO_PKG_TYPE=pacman LANDO_SUDO_PASSWORD=
    node_js: '10'
  - os: linux
    env: LANDO_PKG_TYPE=rpm LANDO_SUDO_PASSWORD=
    node_js: '10'
  - os: linux
    env: LANDO_PKG_TYPE=deb LANDO_SUDO_PASSWORD=
    node_js: '10'
  - os: osx
    osx_image: xcode11.2
    env: LANDO_PKG_TYPE=dmg LANDO_SUDO_PASSWORD=
    node_js: '10'
services:
  - docker
sudo: required
cache:
  yarn: true
  directories:
    - node_modules

script:
  # Push out a latest-dev and commit hash package for all commits to master
  - if [ -z "$TRAVIS_TAG" ] && [[ "$TRAVIS_BRANCH" == "master" ]] ; then cp -rf dist/lando.$LANDO_PKG_TYPE release/lando-latest-dev.$LANDO_PKG_TYPE; fi
  - if [ -z "$TRAVIS_TAG" ] && [[ "$TRAVIS_BRANCH" == "master" ]] ; then cp -rf dist/lando.$LANDO_PKG_TYPE release/lando-$TRAVIS_COMMIT-dev.$LANDO_PKG_TYPE; fi
  # Push out a versioned and stable package for tags
  - if [ ! -z "$TRAVIS_TAG" ]; then cp -rf dist/lando.$LANDO_PKG_TYPE release/lando-$TRAVIS_TAG.$LANDO_PKG_TYPE; fi
  - if [ ! -z "$TRAVIS_TAG" ]; then cp -rf dist/lando.$LANDO_PKG_TYPE release/lando-stable.$LANDO_PKG_TYPE; fi

notifications:
  email:
    recipients:
      - mike@thinktandem.io
    on_failure: always
deploy:
  - provider: releases
    api_key:
      secure: UXDea6KLTOOiUaUfhYqE7stUY74VE2gOdi3No5NscD0Lg3xB/EMf1wzpVe2nuTpjn1CbDBsGXXHqRRpy2IZj6qp21D39+Wygznv9PpSGPgTAB2ZHRYhpux1Qf/HxD8R/NhvISNMXukNLyd66OyiJlz5RWoLWQvLIiJgT1Uczc3Sj8iOJOmYaxQZku/3/q/LmjKKHVJ9vq7ail4l4SoNmLqh6sdDt9utJtavWHMa0hN5kF+CwoV5Vk/z2RFzYNInGwlJggwV7Y/Kf3TmOQv0CiKgxdEQqR8LfTDGIvkxFwpPSf7JnQYnsZWcOWW08oousN7tjc1L1ow2dzPnT2zRYNyx73FwkjWtZ7SLQCkU95pq6FgSy31+w6iWU6Rvwd9mgdX4sfxgdwxLwiF38Rki5TxXtMRGWW1qYRYvnCcc7gpPUPFv0PzsQYZiFSGxMF3uKdKxmKzYd+tfCMvE5YhfkDtCM+LeJBlSL5hZspMUezXEFtiKSv7fDmBKtGGFUsEruNqMphKEbH1kY1UT9SXUu+uxWN40ciJTXfQXJAGMSh34WkZFAgEP/r61+SZDlpuyYPQ8l8fOOcX2uaJYD0LJBSERVmVAX00SNxWSVdTTGibadRXWWuJ4gd4PGCXUhSJI9r1QLfMLyZtt5P3i9SUL2X4cO9isKysBjOq/5DZXjqq0=
    file: release/lando-$TRAVIS_TAG.$LANDO_PKG_TYPE
    skip_cleanup: true
    on:
      repo: lando/lando
      tags: true
  - provider: s3
    access_key_id: AKIAJXCGUYNMSXQPAKYQ
    secret_access_key:
      secure: HstC04mBeuucF2PseyrNLXGZlt5WQ23iwWRrkh4rWTuqq2F4tKkTc+pCB6+Kx64ZE3OGx5T2KdyPOPhLYJOPmYhtTtE0RFI4oF2kEUxvLjTRLrXqDNHKL47PZ5Vel4Z/MTTfWka0M7wCxslBsbomPhO3ljUxlcqChqsh+VT+3JEFYJw4JmEbWHGQ/GnIdTkAksvMfiOFbZHGK+14NjKic9BOwqeBiItSLcydAzURKZOUmcp+u5dNGhHuM+fb98zenhxFIMp75ErwiENv5ER1ja42C+Hyveu3wWc/QIlZHarMULRlH+Zq3yDUCOeOoFjIgeb+H7MGVots8igGIZ4h17/eU8lAO6uRYLLKup/T87CH82VjMDYEDbwsr3XM6f20q/5Fk2dr1XLo+xwhFadIlpJgsbPpmGHu+QuuYczlqdGzw3Qn1IAzU9L7aitjmNQ1ReSGySjlD8sN0nNT7OJYW/4cdy9+RcoYpH4+dbNzjq9DXubJe1EeYQagd/7ebnHvazg5/5Av2whn/F5YjObwno+JrEDzgD2H0pOWfEVBjGT1uOaDIO7Itn1KTJl+gV9Uv+QJ0G/1wP3fnL3KOzMqqFATubtgBUqe12VQ39jUALmgfBKEdXMF2tojwtHkP4b+vQUszpkGxpNih4JmyJYEgc0CZTSNxQP0m+j+3HH/jDc=
    bucket: files.devwithlando.io
    local-dir: release
    acl: public_read
    region: us-west-2
    skip_cleanup: true
    on:
      repo: lando/lando
      all_branches: true
after_success: yarn coverage


    # Test
    - stage: test
      name: Unit Tests - Linux
      before_script: node bin/lando.js version
      script: yarn test:unit
      if: type = pull_request
    - name: Unit Tests - macOS
      os: osx
      osx_image: xcode11.2
      before_script: node bin/lando.js version
      script: yarn test:unit
      if: type = pull_request
    - name: Unit Tests - Windoze
      os: windows
      before_script: node bin/lando.js version
      script: yarn test:unit
      env: YARN_GPG=no GRADLE_OPTS=-Dorg.gradle.daemon=false
      if: type = pull_request

    # Build
    # MacOS builds
    - stage: Build
      name: CLI Binary - macOS
      os: osx
      osx_image: xcode11.2
      script: |
        if [[ "$LANDO_CODE_CHANGED" == "true" ]] ; then
          yarn pkg:cli
          ./dist/cli/lando-* version
        fi
      if: type = push
    - name: Installer - DMG
      os: osx
      osx_image: xcode11.2
      env: LANDO_PKG_TYPE=dmg APPLE_NO_NOTARIZE=notgonnadoit
      before_script: ./scripts/import-apple-keys.sh
      script: |
        if [[ "$LANDO_INSTALLER_CHANGED" == "true" ]] ; then
          mkdir release
          yarn pkg:full
        fi
      if: type = push

    # Windoze builds
    - name: CLI Binary - Windoze
      os: windows
      env: YARN_GPG=no GRADLE_OPTS=-Dorg.gradle.daemon=false
      script: |
        if [[ "$LANDO_CODE_CHANGED" == "true" ]] ; then
          yarn pkg:cli
          ./dist/cli/lando-* version
        fi
      if: type = push
    - name: Installer - EXE
      os: windows
      env: YARN_GPG=no GRADLE_OPTS=-Dorg.gradle.daemon=false LANDO_PKG_TYPE=exe
      before_script:
        - git config --global core.autocrlf true
        - choco install innosetup --version=5.5.9 --allow-empty-checksums
      script: |
        if [[ "$LANDO_INSTALLER_CHANGED" == "true" ]] ; then
          mkdir release
          yarn pkg:full
        fi
      if: type = push

    # Linux builds
    - name: CLI Binary - Linux
      script: |
        if [[ "$LANDO_CODE_CHANGED" == "true" ]] ; then
          yarn pkg:cli
          ./dist/cli/lando-* version
        fi
      if: type = push
    - name: Installer - PACMAN
      env: LANDO_PKG_TYPE=pacman
      script: |
        if [[ "$LANDO_INSTALLER_CHANGED" == "true" ]] ; then
          mkdir release
          yarn pkg:full
        fi
      if: type = push
    - name: Installer - RPM
      env: LANDO_PKG_TYPE=rpm
      script: |
        if [[ "$LANDO_INSTALLER_CHANGED" == "true" ]] ; then
          mkdir release
          yarn pkg:full
        fi
      if: type = push
    - name: Installer - DEB
      env: LANDO_PKG_TYPE=deb
      script: |
        if [[ "$LANDO_INSTALLER_CHANGED" == "true" ]] ; then
          mkdir release
          yarn pkg:full
        fi
      if: type = push

    # Web builds
    - name: API
      script: if [[ "$LANDO_API_CHANGED" == "true" ]] ; then true; fi
      if: type = push
    - name: Blog
      script: if [[ "$LANDO_BLOG_CHANGED" == "true" ]] ; then yarn build:blog; fi
      if: type = push
    - name: Documentation
      script: if [[ "$LANDO_DOCS_CHANGED" == "true" ]] ; then yarn build:docs; fi
      if: type = push
    - name: Events
      script: if [[ "$LANDO_EVENTS_CHANGED" == "true" ]] ; then yarn build:events; fi
      if: type = push
    - name: Metrics
      script: if [[ "$LANDO_METRICS_CHANGED" == "true" ]] ; then true; fi
      if: type = push
    - name: Website
      script: if [[ "$LANDO_SITE_CHANGED" == "true" ]] ; then yarn build:site; fi
      if: type = push
