language: node_js
node_js: 10
dist: xenial
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    # Test
    - stage: test
      name: Unit Tests - Linux
      os: linux
      dist: xenial
      before_script: ./scripts/travis-env.sh
      install: yarn
      script: yarn test
      if: env(TRAVIS_COMMIT_RANGE) IS NOT blank
    - name: Unit Tests - macOS
      os: osx
      osx_image: xcode11.2
      before_script: ./scripts/travis-env.sh
      install: yarn
      script: yarn test
    - name: Unit Tests - Windoze
      os: windows
      before_script: ./scripts/travis-env.sh
      install: yarn
      script: yarn test
    - stage: deploy
      name: "Deploy to GCP"
      script: |
        ./scripts/travis-env.sh
        node -v
      if: env(LANDO) IS present
stages:
  - test
  - deploy
