cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      name: Unit Tests
      os: linux
      dist: xenial
      node_js: 10
      before_script: ./scripts/travis-env.sh
      script: env
    - name: Integration Tests
      node_js: 10
      install: skip
      script: |
        env
        echo "things"
    - name: Unit Tests macOS
      os: osx
      osx_image: xcode11.2
      node_js: 10
      script: true
    - name: Unit Tests windoze
      os: windows
      node_js: 10
      script: true
    - stage: deploy
      node_js: 10
      name: "Deploy to GCP"
      script: ./scripts/travis-env.sh
      if: env(LANDO) IS present
stages:
  - test
  - deploy
