plugins:
  - lando-core
  - lando-engine
  # - lando-events
  # - lando-proxy
  # - lando-recipes
  # - lando-services
  # - lando-test
  # - lando-tooling
stats:
  - report: true
    url: https://metrics.devwithlando.io
