name: lando-mysql
services:
  defaults:
    type: mysql
    overrides:
      command: tail -f /dev/null
  patch:
    type: mysql:5.7.24
    overrides:
      command: tail -f /dev/null
  custom:
    type: mysql:8.0
    portforward: true
    creds:
      user: pirog
      password: password
      database: stuff
    config:
      database: my.cnf
tooling:
  mysql:
    service: custom
    cmd: mysql -uroot
