name: lando-mysql
services:
  defaults:
    type: mysql
  patch:
    type: mysql:5.7.24
  custom:
    type: mysql:8.0
    portforward: true
    creds:
      user: pirog
      password: password
      database: stuff
    config:
      database: my.cnf
  custom_auth:
    type: mysql:8.0
    authentication: mysql_native_password
tooling:
  mysql:
    cmd: mysql
    service: :host
    options:
      host:
        description: The database service to use
        default: defaults
        alias:
          - h

