version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
      # @todo: once we have more tests running lets buy the below and
      # set up max parallelism
      # docker_layer_caching: true
      parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install node
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sleep 5
            sudo apt-get install -y nodejs
      - run:
          name: Install yarn
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update -y && sudo apt-get install yarn -y
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Verify we have the things we need to start
          command: |
            docker -v
            docker-compose -v
            node -v
            yarn -v
            node ~/project/bin/lando.js version
      - run:
          name: Run func test
          command: |
            node ~/project/scripts/generate-tests.js
            TESTFILES=$(circleci tests split ~/project/test/func/split-file.txt)
            echo ${TESTFILES}

      #- run:
      #    name: Functional Tests
      #    command: yarn test:functional
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
