version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
      # @todo: once we have more tests running lets buy the below and
      # set up max parallelism
      # docker_layer_caching: true
    parallelism: 8
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Take this thing into hyperspace
          command: |
            curl -Ls https://github.com/lando/hyperdrive/releases/download/v0.5.1/hyperdrive > /tmp/hyperdrive
            chmod +x /tmp/hyperdrive
            /tmp/hyperdrive -y
      - run:
          name: Switch lando over to source
          command: |
            cp -f ~/project/.circleci/lando.yml ~/project/config.yml
            node ~/project/bin/lando.js config
            sudo rm -f /usr/local/bin/lando
            sudo ln -sf ~/project/bin/lando.js /usr/local/bin/lando
            which lando
      - run:
          name: Run func test
          command: |
            yarn leia "examples/**/*.md" test -r 6 -s Start -s Boot -s Spin -s Launch -s 'This is the dawning' -t Test -t Validat -t Verif -t Sanity -c Clean -c Kill -c Tear -c Destruct -c Destroy -c Nuke -c Blow -c Burn -c Purge --split-file
            echo $(circleci tests split ~/project/test/split-file.txt)
            yarn mocha --timeout 900000 $(circleci tests split ~/project/test/split-file.txt)
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
