version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201710-01
      docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - lando-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - lando-{{ .Branch }}-
            - lando-
      - run:
          name: Take this thing into hyperspace
          environment:
            TERM: xterm
          command: |
            # Spoof the public key
            ssh-keygen -t rsa -N "" -C "spoof@circle" -f "$HOME/.ssh/spoofkey"
            mv "$HOME/.ssh/spoofkey.pub" "$HOME/.ssh/id_rsa.pub"
            # Hyperdrive
            curl -Ls https://github.com/lando/hyperdrive/releases/download/v0.5.1/hyperdrive > /tmp/hyperdrive
            chmod +x /tmp/hyperdrive
            /tmp/hyperdrive -y --name "Lando System" --email landobot@devwithlando.io
            # @TODO: anyway hyperdrive can assert dominance here?
            sudo ln -sf /usr/bin/nodejs /opt/circleci/.nvm/versions/node/v6.1.0/bin/node
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Switch lando over to binary built from source
          command: |
            sudo mv -f /usr/local/bin/lando /usr/local/bin/lando.stable
            yarn pkg:cli
            sudo mv dist/cli/* /usr/local/bin/lando
            lando version
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: lando-{{ .Branch }}-{{ checksum "yarn.lock" }}
  test:
    machine:
      image: circleci/classic:201710-01
      docker_layer_caching: true
    parallelism: 8
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Disable usage and error reporting
          command: |
            # Disable usage reporting
            cp -f ~/project/.circleci/lando.yml ~/project/config.yml
            # Disable error reporting
            mkdir -p ~/.lando/cache
            echo false > ~/.lando/cache/report_errors
      - run:
          name: Run func test
          command: |
            yarn generate-tests
            yarn mocha --timeout 900000 $(circleci tests split ~/project/test/split-file.txt)
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
