version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
      # docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install deps
          command: yarn
      - run:
          name: Verify versions of things
          command: |
            docker -v
            docker-compose -v
            node -v
            lando version
      - run:
          name: Unit Tests
          command: yarn test:unit
      #- run:
      #    name: Functional Tests
      #    command: yarn test:functional
