version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
      # @todo: once we have more tests running lets buy the below and
      # set up max parallelism
      # docker_layer_caching: true
    parallelism: 8
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Prep the hyperdrive
          command: |
            sudo apt -y update
            # See https://discuss.circleci.com/t/cannot-install-php-7-1-on-machine-because-of-locked-var-lib-dpkg-lock-file/24639/5
            sudo rm -rf /var/lib/apt/lists/lock
            sudo rm -rf /var/cache/apt/archives/lock
            sudo rm -rf /var/lib/dpkg/lock
            sudo apt -y install bc
      - run:
          name: Take this thing into hyperspace
          environment:
            TERM: xterm
          command: |
            # Spoof the public key
            # @TODO: need a better check for ssh-keys, pub and private
            # @TODO: or a way to disable steps?
            ssh-keygen -t rsa -N "" -C "spoof@circle" -f "$HOME/.ssh/spoofkey"
            mv "$HOME/.ssh/spoofkey.pub" "$HOME/.ssh/id_rsa.pub"
            curl -Ls https://github.com/lando/hyperdrive/releases/download/v0.5.1/hyperdrive > /tmp/hyperdrive
            chmod +x /tmp/hyperdrive
            /tmp/hyperdrive -y --name "Mike Pirog" --email mike@thinktandem.io
            # TODO: anyway hyperdrive can assert dominance here?
            sudo ln -sf /usr/bin/nodejs /opt/circleci/.nvm/versions/node/v6.1.0/bin/node
            # Verify our hyperdrive is purring like a lothcat
            /tmp/hyperdrive -y
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Switch lando over to source
          command: |
            cp -f ~/project/.circleci/lando.yml ~/project/config.yml
            node ~/project/bin/lando.js config
            sudo rm -f /usr/local/bin/lando
            sudo ln -sf ~/project/bin/lando.js /usr/local/bin/lando
            which lando
      - run:
          name: Run func test
          command: |
            yarn leia "examples/**/*.md" test -r 6 -s Start -s Boot -s Spin -s Launch -s 'This is the dawning' -t Test -t Validat -t Verif -t Sanity -c Clean -c Kill -c Tear -c Destruct -c Destroy -c Nuke -c Blow -c Burn -c Purge --split-file
            echo $(circleci tests split ~/project/test/split-file.txt)
            yarn mocha --timeout 900000 $(circleci tests split ~/project/test/split-file.txt)
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
