name: lando-compose
services:
  custom-service:
    type: compose
    services:
      image: drupal:8
      command: docker-php-entrypoint apache2-foreground
      ports:
        - '80'
    volumes:
      my-volume:
    networks:
      my-network:
  custom-service2:
    type: compose
    services:
      image: pirog/custom:hyperion
      build: ./custom
      networks:
        - my-network
      volumes:
        - ./chaosmonkey.txt:/tmp/monkeysee.txt
      command: tail -f /dev/null
