name: lando-solr
services:
  defaults:
    type: solr
  patch:
    type: solr:5.5.5
    core: solo
  custom:
    type: solr:7.6
    core: freedom
    config:
      dir: config
  legacy4:
    type: solr:4
  helper:
    type: php
    via: cli
tooling:
  post-record-defaults:
    cmd: "curl http://defaults:8983/solr/lando/update -H 'Content-Type: text/xml' -T '/app/test.xml' -X POST"
    service: helper
  post-record-patch:
    cmd: "curl http://patch:8983/solr/solo/update -H 'Content-Type: text/xml' -T '/app/test.xml' -X POST"
    service: helper
