# The name of my app
name: nginx

# Give me http://nginx.lndo.site and https://nginx.lndo.site
proxy:
  appserver:
    - nginx.lndo.site

# Configure my services
services:

  # Create an nginx service called "appserver"
  appserver:

    # Use nginx version
    type: nginx

    # Turn on SSL
    ssl: true

    # Optionally specify a webroot if your index.html is in a subdirectory
    webroot: www

    # Optionally use our own config files
    config:

      # Use custom nginx server config located in config/server.conf relative
      # to our app root
      server: config/server.conf

      # Use custom nginx http config located in config/http.conf relative
      # to our app root
      vhosts: config/custom.conf

      params: config/params