name: lando-nginx
proxy:
  custom:
    - nginx.lndo.site
    - nginx.lndo.site/api
    - www.nginx.lndo.site
    - "*-nginx.lndo.site"
    - "wild.*.nginx.lndo.site"
    - "*.sub.nginx.lndo.site"
    - "lets.combine.*.lndo.site:80/everything/for-real"
services:
  defaults:
    type: nginx
  patch:
    type: nginx:1.14.1
  custom:
    type: nginx
    ssl: true
    webroot: www
    config:
      server: config/server.conf
      vhosts: config/custom.conf
      params: config/params
