name: lando-varnish
services:
  defaults:
    type: varnish
  custom:
    type: varnish:4.1
    backends:
      - appserver
    ssl: true
    config:
      vcl: config/custom.vcl
  customport:
    type: varnish
    backends:
      - backend2
    backend_port: 8000
    ssl: true
  appserver:
    type: nginx
  backend2:
    type: python
    port: 8000
    command: python /app/python.py
