http://{default}/:
  type: redirect
  to: https://{default}/
https://docs.lndo.io/:
  type: redirect
  to: https://{default}/
https://{default}/:
  type: upstream
  upstream: app:http
  cache:
    enabled: true
  ssi:
    enabled: false
