http://docs.devwithlando.io/:
  type: redirect
  to: http://{default}/
http://docs.lndo.io/:
  type: redirect
  to: http://{default}/
http://{default}/:
  type: upstream
  upstream: docs:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
