https://devwithlando.io/:
  type: redirect
  to: https://{default}/
https://docs.devwithlando.io/:
  type: redirect
  to: https://docs.{default}/
https://share.devwithlando.io/:
  type: redirect
  to: https://share.{default}/
https://*.share.devwithlando.io/:
  type: redirect
  to: https://share.{default}/
https://lndo.io/:
  type: redirect
  to: https://{default}/
https://docs.lndo.io/:
  type: redirect
  to: https://docs.{default}/
https://share.lndo.io/:
  type: redirect
  to: https://share.{default}/
https://*.share.lndo.io/:
  type: redirect
  to: https://share.{default}/
https://{default}/:
  type: upstream
  upstream: site:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
https://docs.{default}/:
  type: upstream
  upstream: docs:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
https://share.{default}/:
  type: upstream
  upstream: share:http
  ssi:
    enabled: false
https://*.share.{default}/:
  type: upstream
  upstream: share:http
  ssi:
    enabled: false
