http://docs.lando.dev/:
  type: redirect
  to: http://{default}/
http://docs.lndo.io/:
  type: redirect
  to: http://{default}/
http://{default}/:
  type: upstream
  upstream: app:http
  cache:
    enabled: true
  ssi:
    enabled: false
