# Name of my app
name: apache

# Give me http://apache.lndo.site and https://apache.lndo.site
proxy:
  html:
    - apache.lndo.site

# Build me an apache worthy of the internet
services:

  # You can name this key anything you want.
  html:

    # Use the latest version of apache.
    type: apache

    # Optionally specify a webroot if it is a subdirectory of the appRoot
    webroot: web

    # Turn on SSL
    ssl: true

    # Optionally use a custom apache conf file
    # This should live in your app root and is relative to it
    config:
      server: config/httpd.conf
      vhosts: config/custom.conf
