name: lando-apache
services:
  defaults:
    type: apache
  patch:
    type: apache:2.4.37
  custom:
    type: apache
    webroot: web
    ssl: true
    config:
      server: config/httpd.conf
      vhosts: config/custom.conf
