# Name of my app
name: apache

# Give me http://apache.lndo.site and https://apache.lndo.site
proxy:
  html:
    - apache.lndo.site

# Build me an apache worthy of the internet
services:

  # You can name this key anything you want.
  html:

    # Use the latest version of apache.
    type: apache

    # Optionally specify a webroot if it is a subdirectory of the appRoot
    webroot: web

    # Optionally use a custom apache conf file
    # This should live in your app root and is relative to it
    config:
      server: config/httpd.conf
      vhosts: config/custom.conf

    # Scripts
    scripts:
      - scripts/printenv.sh

    # These are v3 docker compose file overrides. They allow you to provide very
    # precise fine tuning to your app
    # See: https://docs.docker.com/compose/compose-file/
    overrides:
      environment:
        STUFF: THINGS
      ports:
        - '8081:80'
      volumes:
        - ./web:/fuck
      # Uncomment below to use a custom image or Dockerfile build location
      # image: pirog/myapache:2

    # Install server dependencies and packages that your app needs to run
    # These run BEFORE your app boots up and are things that require root access
    # Installing extra php extensions is a good example
    install_dependencies_as_root:
      - apt-get update -y
      - apt-get install vim -y

    # Install app dependencies and packages that your app needs to run
    # These also run BEFORE your app boots up but are things you don't want to
    # install as root.
    # Running `npm install` or `yarn` is a good example
    install_dependencies_as_me:
      - echo "run as me $(whoami)"

    # We encourage you to use events to automate commands that should run AFTER
    # your app starts eg a watch task

    # DEPRECATED BUILD STEPS, these will still run as they did pre-RC1 but we
    # HIGHLY ENCOURAGE you to move to the new build step format above.
    #
    # See https://docs.devwithlando.io/config/build.html#build-steps
    #
    # Note that *_internal steps should not be invoked like they are here
    # these channels are meant only for lando to use programmatically
    run_as_root_internal:
      - echo "run as root internal $(whoami)"
    run_as_root:
      - echo "run as root $(whoami)"
    extras:
      - echo "extras $(whoami)"
    run_internal:
      - echo "run internal $(whoami)"
    run_root:
      - echo "run $(whoami)"
    build:
      - echo "build $(whoami)"
tooling:
  vim:
    service: html