# The name of the app
name: sql-export

# Set up my services
services:

  # Spin up a mariadb container called "database"
  # NOTE: "database" is arbitrary, you could just as well call this "db" or "kanye"
  database:

    # Use the latest version of mysql
    type: mysql
    portforward: true

    # Optionally change the default db credentials
    creds:
      user: mysql
      password: mysql
      database: data1

  # Spin up a secondary database for postgres
  database2:
    portforward: true
    type: postgres

tooling:
  mysql:
    service: :host
    description: Drop into a mysql shell on a database service
    cmd: mysql -u root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
  psql:
    service: :host
    description: Drop into a postgres shell on a database service
    cmd: psql -h localhost -p 5432 -U postgres
    options:
      host:
        description: The database service to use
        default: database2
        alias:
          - h
  'db-export [file]':
    service: :host
    description: Exports database from a database service to a file
    cmd: /helpers/sql-export.sh
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      stdout:
        description: Dump database to stdout
  'db-import <file>':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
