name: trivial-events
compose:
  - compose.yml
events:
  pre-start:
    - web: hostname -A
    - web2: hostname -A
  post-start:
    - web: hostname -A
  post-thing:
    - web: env
tooling:
  thing:
    service: web
    cmd: hostname -A
