name: trivial-services
sharing:
  data:
    local: .
    remote: /usr/share/nginx/html
proxy:
  appserver:
    - port: 80/tcp
      default: true
services:
  appserver:
    type: nginx
    ssl: true
    config:
      server: config/server.conf
